# Generated by Django 5.2.15 on 2026-06-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institution_type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College')], default='school', help_text='School student or college student.', max_length=10),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='College only — semester number (1–8). Leave blank for school.', null=True),
        ),
    ]
