services:
  - type: web
    name: school-management-system
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
