# Generated by Django 5.2.15 on 2026-06-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['institution_type', 'name'], 'verbose_name_plural': 'Classes & courses'},
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='institution_type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College')], default='school', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='program_type',
            field=models.CharField(choices=[('school', 'School (sections only — no semester)'), ('ug_3yr', 'Undergraduate — 3 years / 6 semesters'), ('ug_4yr_integrated', 'Integrated — 4 years / 8 semesters'), ('pg_2yr', 'Post Graduation — 2 years / 4 semesters')], default='school', max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(help_text='School: Std 8, Std 9… · College: BCA, MCA, BBA…', max_length=100),
        ),
    ]
