# Generated by Django 5.2.14 on 2026-05-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (INR)'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Late fee (INR)'),
        ),
        migrations.AlterField(
            model_name='feestructureitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Fee amount in Indian Rupees.', max_digits=10, verbose_name='Amount (INR)'),
        ),
        migrations.AlterField(
            model_name='studentfeeassignment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount (INR)'),
        ),
    ]
