# Generated by Django 5.2.15 on 2026-06-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='College attendance — semester number. Blank for school.', null=True),
        ),
    ]
